function press_buttons_blue(vid, galileo)
    blueG_min = 125;
    blueG_max = 255;
    blueB_min = 175;
    blueB_max = 255;

    % acoes
    APERTA_E_SOLTA_BLUE = char(130);
    APERTA_SEM_SOLTAR_BLUE = char(131);
    SOLTA_BLUE = char(132);

    % tempos
    
    % envia os tempos para o arduino, ou verifica se os tempos
    % estão corretos, caso o arduino já possua o tempo
    [tempo_simples, tempo_rastro] = detect_times(vid);
    tempo_espera = tempo_rastro - tempo_simples;
    configure_arduino_time(galileo, tempo_simples, tempo_rastro);
    
    G = 2;
    B = 3;

    % situacao de rastro das cores
    keys = {'blue'};
    values = [false];
    holding_buttons = containers.Map(keys, values);

    keys = {'blue'};
    values = [uint64(0)];
    holding_times = containers.Map(keys, values);
    
    green_time = tic;
    red_time = tic;
    yellow_time = tic;
    blue_time = tic;
    orange_time = tic;

    while true
        imgO = getdata(vid,1,'uint8');
        bluePixelG = imgO(312,354,G);
        bluePixelB = imgO(312,354,B);
        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% rastro_play %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        
        if( ~holding_buttons('blue') && ...
            (imgO(291,349,B) >= blueB_min && imgO(291,349,B) <= blueB_max) && ...
            (imgO(291,349,G) >= blueG_min && imgO(291,349,G) <= blueG_max) && ...
            (imgO(290,349,B) >= blueB_min && imgO(290,349,B) <= blueB_max) && ...
            (imgO(290,349,G) >= blueG_min && imgO(290,349,G) <= blueG_max) && ...
            (imgO(289,349,B) >= blueB_min && imgO(289,349,B) <= blueB_max) && ...
            (imgO(289,349,G) >= blueG_min && imgO(289,349,G) <= blueG_max) && ...
            (imgO(288,349,B) >= blueB_min && imgO(288,349,B) <= blueB_max) && ...
            (imgO(288,349,G) >= blueG_min && imgO(288,349,G) <= blueG_max) && ...
            (imgO(287,349,B) >= blueB_min && imgO(287,349,B) <= blueB_max) && ...
            (imgO(287,349,G) >= blueG_min && imgO(287,349,G) <= blueG_max) && ...
            (imgO(286,349,B) >= blueB_min && imgO(286,349,B) <= blueB_max) && ...
            (imgO(286,349,G) >= blueG_min && imgO(286,349,G) <= blueG_max) && ...
            (imgO(285,348,B) >= blueB_min && imgO(285,348,B) <= blueB_max) && ...
            (imgO(285,348,G) >= blueG_min && imgO(285,348,G) <= blueG_max) && ...
            (imgO(284,348,B) >= blueB_min && imgO(284,348,B) <= blueB_max) && ...
            (imgO(284,348,G) >= blueG_min && imgO(284,348,G) <= blueG_max) && ...
            (imgO(283,348,B) >= blueB_min && imgO(283,348,B) <= blueB_max) && ...
            (imgO(283,348,G) >= blueG_min && imgO(283,348,G) <= blueG_max) && ...
            (imgO(282,348,B) >= blueB_min && imgO(282,348,B) <= blueB_max) && ...
            (imgO(282,348,G) >= blueG_min && imgO(282,348,G) <= blueG_max) && ...
            (imgO(281,348,B) >= blueB_min && imgO(281,348,B) <= blueB_max) && ...
            (imgO(281,348,G) >= blueG_min && imgO(281,348,G) <= blueG_max) && ...
            (imgO(280,348,B) >= blueB_min && imgO(280,348,B) <= blueB_max) && ...
            (imgO(280,348,G) >= blueG_min && imgO(280,348,G) <= blueG_max) && ...
            (imgO(279,348,B) >= blueB_min && imgO(279,348,B) <= blueB_max) && ...
            (imgO(279,348,G) >= blueG_min && imgO(279,348,G) <= blueG_max) )
            
            %segura botao
            holding_buttons('blue') = true;
            holding_times('blue') = tic;
            fprintf(galileo,'%c', APERTA_SEM_SOLTAR_BLUE);  
        end

        %quando o rastro acaba solta
        %Se esta_apertando e nao ha mais rastro passando
        if( holding_buttons('blue') && ...
            ~(imgO(312,311,B) >= blueB_min && imgO(312,311,B) <= blueB_max && ...
            imgO(312,311,G) >= blueG_min && imgO(312,311,G) <= blueG_max) && ...
            toc(holding_times('blue')) > tempo_espera)

            holding_buttons('blue') = false;
            fprintf(galileo,'%c', SOLTA_BLUE);  

        end

        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% rastro_play %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

        %detect blue
        if(bluePixelG >= blueG_min && bluePixelG <= blueG_max && ...
           bluePixelB >= blueB_min && bluePixelB <= blueB_max && ...
           toc(blue_time) > tempo_espera &&  ~holding_buttons('blue'))
           fprintf(galileo,'%c', APERTA_E_SOLTA_BLUE);
           blue_time = tic;
        end
    end
end