function press_buttons_yellow(vid, galileo)
    yellowR_min = 175;
    yellowR_max = 255;
    yellowG_min = 150;
    yellowG_max = 255;

    APERTA_E_SOLTA_YELLOW = char(120);
    APERTA_SEM_SOLTAR_YELLOW = char(121);
    SOLTA_YELLOW = char(122);

    [tempo_simples, tempo_rastro] = detect_times(vid);
    tempo_espera = tempo_rastro - tempo_simples;
    configure_arduino_time(galileo, tempo_simples, tempo_rastro);
    
    R = 1;
    G = 2;

    % situacao de rastro das cores
    keys = {'yellow'};
    values = [false];
    holding_buttons = containers.Map(keys, values);

    keys = {'yellow'};
    values = [uint64(0)];
    holding_times = containers.Map(keys, values);
    
    yellow_time = tic;

    while true
        imgO = getdata(vid,1,'uint8');
        yellowPixelR = imgO(312,311,R);
        yellowPixelG = imgO(312,311,G);

        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% rastro_play %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

        if( ~holding_buttons('yellow') && ...
            (imgO(293,312,R) >= yellowR_min && imgO(293,312,R) <= yellowR_max) && ...
            (imgO(293,312,G) >= yellowG_min && imgO(293,312,G) <= yellowG_max) && ...
            (imgO(292,312,R) >= yellowR_min && imgO(292,312,R) <= yellowR_max) && ...
            (imgO(292,312,G) >= yellowG_min && imgO(292,312,G) <= yellowG_max) && ...
            (imgO(291,312,R) >= yellowR_min && imgO(291,312,R) <= yellowR_max) && ...
            (imgO(291,312,G) >= yellowG_min && imgO(291,312,G) <= yellowG_max) && ...
            (imgO(290,312,R) >= yellowR_min && imgO(290,312,R) <= yellowR_max) && ...
            (imgO(290,312,G) >= yellowG_min && imgO(290,312,G) <= yellowG_max) && ...
            (imgO(289,312,R) >= yellowR_min && imgO(289,312,R) <= yellowR_max) && ...
            (imgO(289,312,G) >= yellowG_min && imgO(289,312,G) <= yellowG_max) && ...
            (imgO(288,312,R) >= yellowR_min && imgO(288,312,R) <= yellowR_max) && ...
            (imgO(288,312,G) >= yellowG_min && imgO(288,312,G) <= yellowG_max) && ...
            (imgO(287,312,R) >= yellowR_min && imgO(287,312,R) <= yellowR_max) && ...
            (imgO(287,312,G) >= yellowG_min && imgO(287,312,G) <= yellowG_max) && ...
            (imgO(286,312,R) >= yellowR_min && imgO(286,312,R) <= yellowR_max) && ...
            (imgO(286,312,G) >= yellowG_min && imgO(286,312,G) <= yellowG_max) && ...
            (imgO(285,312,R) >= yellowR_min && imgO(285,312,R) <= yellowR_max) && ...
            (imgO(285,312,G) >= yellowG_min && imgO(285,312,G) <= yellowG_max) && ...
            (imgO(284,312,R) >= yellowR_min && imgO(284,312,R) <= yellowR_max) && ...
            (imgO(284,312,G) >= yellowG_min && imgO(284,312,G) <= yellowG_max) && ...
            (imgO(283,312,R) >= yellowR_min && imgO(283,312,R) <= yellowR_max) && ...
            (imgO(283,312,G) >= yellowG_min && imgO(283,312,G) <= yellowG_max) && ...
            (imgO(282,312,R) >= yellowR_min && imgO(282,312,R) <= yellowR_max) && ...
            (imgO(282,312,G) >= yellowG_min && imgO(282,312,G) <= yellowG_max) && ...
            (imgO(281,312,R) >= yellowR_min && imgO(281,312,R) <= yellowR_max) && ...
            (imgO(281,312,G) >= yellowG_min && imgO(281,312,G) <= yellowG_max) )
            
            %segura botao
            holding_buttons('yellow') = true;
            holding_times('yellow') = tic;
            fprintf(galileo,'%c', APERTA_SEM_SOLTAR_YELLOW);  
        end
    
        %quando o rastro acaba solta
        %Se esta_apertando e nao ha mais rastro passando
        if( holding_buttons('yellow') && ...
            ~(imgO(312,311,R) >= yellowR_min && imgO(312,311,R) <= yellowR_max && ...
              imgO(312,311,G) >= yellowG_min && imgO(312,311,G) <= yellowG_max) && ...
            toc(holding_times('yellow')) > tempo_espera)
    
            holding_buttons('yellow') = false;
            fprintf(galileo,'%c', SOLTA_YELLOW);  
    
        end

        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% rastro_play %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

        %detect yellow
        if(yellowPixelR >= yellowR_min && yellowPixelR <= yellowR_max && ...
           yellowPixelG >= yellowG_min && yellowPixelG <= yellowG_max && ...
           toc(yellow_time) > tempo_espera &&  ~holding_buttons('yellow'))
           fprintf(galileo,'%c', APERTA_E_SOLTA_YELLOW);
           yellow_time = tic;
        end
    end
end