classdef Playgame
    properties (Constant)
        % colors configuration
        red_min         = 175;
        red_max         = 255;
        green_min       = 175;
        green_max       = 255;
        yellowR_min     = 175;
        yellowR_max     = 255;
        yellowG_min     = 150;
        yellowG_max     = 255;
        blueG_min       = 125;
        blueG_max       = 255;
        blueB_min       = 175;
        blueB_max       = 255;
        orangeR_min     = 175;
        orangeR_max     = 255;
        orangeG_min     = 95;
        orangeG_max     = 255;
    end

    properties (Access = public)
        note_green      = false;
        note_red        = false;
        note_blue       = false;
        note_yellow     = false;
        note_orange     = false;

        trail_green     = false;
        trail_red       = false;
        trail_blue      = false;
        trail_yellow    = false;
        trail_orange    = false;

        greenPixel;
        redPixel;
        yellowPixelR;
        yellowPixelG;
        bluePixelG;
        bluePixelB;
        orangePixelR;
        orangePixelG;

        arduino;
        imgO;
    end

    methods

        function playgame = set_up(playgame)
            %detect green
            if ((playgame.greenPixel >= playgame.green_min) && (playgame.greenPixel <= playgame.green_max))
                find_trail_green();
                playgame.note_green = true;
            end

            %detect red
            if ((playgame.redPixel >= playgame.red_min) && (playgame.redPixel <= playgame.red_max))
                find_trail_red();
                playgame.note_red = true;
            end

            %detect yellow
            if ((playgame.yellowPixelR >= playgame.yellowR_min) && (playgame.yellowPixelR <= playgame.yellowR_max) && ...
                (playgame.yellowPixelG >= playgame.yellowG_min) && (playgame.yellowPixelG <= playgame.yellowG_max))
                find_trail_yellow();
                playgame.note_yellow = true;
            end

            %detect blue
            if ((playgame.bluePixelG >= playgame.blueG_min) && (playgame.bluePixelG <= playgame.blueG_max) && ...
                (playgame.bluePixelB >= playgame.blueB_min) && (playgame.bluePixelB <= playgame.blueB_max))
                find_trail_blue();
                playgame.note_blue = true;
            end

            %detect orange
            if ((playgame.orangePixelR >= playgame.orangeR_min) && (playgame.orangePixelR <= playgame.orangeR_max) && ...
                (playgame.orangePixelG >= playgame.orangeG_min) && (playgame.orangePixelG <= playgame.orangeG_max))
                find_trail_orange();
                playgame.note_orange = true;
            end
        end
        
        function playgame = find_trail_green(playgame)
            if ((playgame.imgO(293,238,playgame.G) >= playgame.green_min) && (playgame.imgO(293,238,playgame.G) <= playgame.green_max) && ...
                (playgame.imgO(292,238,playgame.G) >= playgame.green_min) && (playgame.imgO(292,238,playgame.G) <= playgame.green_max) && ...
                (playgame.imgO(291,239,playgame.G) >= playgame.green_min) && (playgame.imgO(291,239,playgame.G) <= playgame.green_max) && ...
                (playgame.imgO(290,239,playgame.G) >= playgame.green_min) && (playgame.imgO(290,239,playgame.G) <= playgame.green_max) && ...
                (playgame.imgO(289,239,playgame.G) >= playgame.green_min) && (playgame.imgO(289,239,playgame.G) <= playgame.green_max) && ...
                (playgame.imgO(288,240,playgame.G) >= playgame.green_min) && (playgame.imgO(288,240,playgame.G) <= playgame.green_max) && ...
                (playgame.imgO(287,240,playgame.G) >= playgame.green_min) && (playgame.imgO(287,240,playgame.G) <= playgame.green_max) && ...
                (playgame.imgO(286,240,playgame.G) >= playgame.green_min) && (playgame.imgO(286,240,playgame.G) <= playgame.green_max) && ...
                (playgame.imgO(285,241,playgame.G) >= playgame.green_min) && (playgame.imgO(285,241,playgame.G) <= playgame.green_max) && ...
                (playgame.imgO(284,241,playgame.G) >= playgame.green_min) && (playgame.imgO(284,241,playgame.G) <= playgame.green_max) && ...
                (playgame.imgO(283,241,playgame.G) >= playgame.green_min) && (playgame.imgO(283,241,playgame.G) <= playgame.green_max) && ...
                (playgame.imgO(282,242,playgame.G) >= playgame.green_min) && (playgame.imgO(282,242,playgame.G) <= playgame.green_max) && ...
                (playgame.imgO(281,243,playgame.G) >= playgame.green_min) && (playgame.imgO(281,243,playgame.G) <= playgame.green_max))
                send_command(playgame.arduino, "0000010000000000");
                playgame.trail_green = true;
            end
        end

        function playgame = find_trail_red(playgame)
            if ((playgame.imgO(293,275,playgame.R) >= playgame.red_min) && (playgame.imgO(293,275,playgame.R) <= playgame.red_max) && ...
                (playgame.imgO(292,275,playgame.R) >= playgame.red_min) && (playgame.imgO(292,275,playgame.R) <= playgame.red_max) && ...
                (playgame.imgO(291,275,playgame.R) >= playgame.red_min) && (playgame.imgO(291,275,playgame.R) <= playgame.red_max) && ...
                (playgame.imgO(290,276,playgame.R) >= playgame.red_min) && (playgame.imgO(290,276,playgame.R) <= playgame.red_max) && ...
                (playgame.imgO(289,276,playgame.R) >= playgame.red_min) && (playgame.imgO(289,276,playgame.R) <= playgame.red_max) && ...
                (playgame.imgO(288,276,playgame.R) >= playgame.red_min) && (playgame.imgO(288,276,playgame.R) <= playgame.red_max) && ...
                (playgame.imgO(287,276,playgame.R) >= playgame.red_min) && (playgame.imgO(287,276,playgame.R) <= playgame.red_max) && ...
                (playgame.imgO(286,276,playgame.R) >= playgame.red_min) && (playgame.imgO(286,276,playgame.R) <= playgame.red_max) && ...
                (playgame.imgO(285,277,playgame.R) >= playgame.red_min) && (playgame.imgO(285,277,playgame.R) <= playgame.red_max) && ...
                (playgame.imgO(284,277,playgame.R) >= playgame.red_min) && (playgame.imgO(284,277,playgame.R) <= playgame.red_max) && ...
                (playgame.imgO(283,277,playgame.R) >= playgame.red_min) && (playgame.imgO(283,277,playgame.R) <= playgame.red_max) && ...
                (playgame.imgO(282,277,playgame.R) >= playgame.red_min) && (playgame.imgO(282,277,playgame.R) <= playgame.red_max) && ...
                (playgame.imgO(281,278,playgame.R) >= playgame.red_min) && (playgame.imgO(281,278,playgame.R) <= playgame.red_max))
                send_command(playgame.arduino, "0000001000000000");
                playgame.trail_red = true;
            end
        end

        function playgame = find_trail_yellow(playgame)
            if ((playgame.imgO(293,312,playgame.R) >= playgame.yellowR_min) && (playgame.imgO(293,312,playgame.R) <= playgame.yellowR_max) && ...
                (playgame.imgO(293,312,playgame.G) >= playgame.yellowG_min) && (playgame.imgO(293,312,playgame.G) <= playgame.yellowG_max) && ...
                (playgame.imgO(292,312,playgame.R) >= playgame.yellowR_min) && (playgame.imgO(292,312,playgame.R) <= playgame.yellowR_max) && ...
                (playgame.imgO(292,312,playgame.G) >= playgame.yellowG_min) && (playgame.imgO(292,312,playgame.G) <= playgame.yellowG_max) && ...
                (playgame.imgO(291,312,playgame.R) >= playgame.yellowR_min) && (playgame.imgO(291,312,playgame.R) <= playgame.yellowR_max) && ...
                (playgame.imgO(291,312,playgame.G) >= playgame.yellowG_min) && (playgame.imgO(291,312,playgame.G) <= playgame.yellowG_max) && ...
                (playgame.imgO(290,312,playgame.R) >= playgame.yellowR_min) && (playgame.imgO(290,312,playgame.R) <= playgame.yellowR_max) && ...
                (playgame.imgO(290,312,playgame.G) >= playgame.yellowG_min) && (playgame.imgO(290,312,playgame.G) <= playgame.yellowG_max) && ...
                (playgame.imgO(289,312,playgame.R) >= playgame.yellowR_min) && (playgame.imgO(289,312,playgame.R) <= playgame.yellowR_max) && ...
                (playgame.imgO(289,312,playgame.G) >= playgame.yellowG_min) && (playgame.imgO(289,312,playgame.G) <= playgame.yellowG_max) && ...
                (playgame.imgO(288,312,playgame.R) >= playgame.yellowR_min) && (playgame.imgO(288,312,playgame.R) <= playgame.yellowR_max) && ...
                (playgame.imgO(288,312,playgame.G) >= playgame.yellowG_min) && (playgame.imgO(288,312,playgame.G) <= playgame.yellowG_max) && ...
                (playgame.imgO(287,312,playgame.R) >= playgame.yellowR_min) && (playgame.imgO(287,312,playgame.R) <= playgame.yellowR_max) && ...
                (playgame.imgO(287,312,playgame.G) >= playgame.yellowG_min) && (playgame.imgO(287,312,playgame.G) <= playgame.yellowG_max) && ...
                (playgame.imgO(286,312,playgame.R) >= playgame.yellowR_min) && (playgame.imgO(286,312,playgame.R) <= playgame.yellowR_max) && ...
                (playgame.imgO(286,312,playgame.G) >= playgame.yellowG_min) && (playgame.imgO(286,312,playgame.G) <= playgame.yellowG_max) && ...
                (playgame.imgO(285,312,playgame.R) >= playgame.yellowR_min) && (playgame.imgO(285,312,playgame.R) <= playgame.yellowR_max) && ...
                (playgame.imgO(285,312,playgame.G) >= playgame.yellowG_min) && (playgame.imgO(285,312,playgame.G) <= playgame.yellowG_max) && ...
                (playgame.imgO(284,312,playgame.R) >= playgame.yellowR_min) && (playgame.imgO(284,312,playgame.R) <= playgame.yellowR_max) && ...
                (playgame.imgO(284,312,playgame.G) >= playgame.yellowG_min) && (playgame.imgO(284,312,playgame.G) <= playgame.yellowG_max) && ...
                (playgame.imgO(283,312,playgame.R) >= playgame.yellowR_min) && (playgame.imgO(283,312,playgame.R) <= playgame.yellowR_max) && ...
                (playgame.imgO(283,312,playgame.G) >= playgame.yellowG_min) && (playgame.imgO(283,312,playgame.G) <= playgame.yellowG_max) && ...
                (playgame.imgO(282,312,playgame.R) >= playgame.yellowR_min) && (playgame.imgO(282,312,playgame.R) <= playgame.yellowR_max) && ...
                (playgame.imgO(282,312,playgame.G) >= playgame.yellowG_min) && (playgame.imgO(282,312,playgame.G) <= playgame.yellowG_max) && ...
                (playgame.imgO(281,312,playgame.R) >= playgame.yellowR_min) && (playgame.imgO(281,312,playgame.R) <= playgame.yellowR_max) && ...
                (playgame.imgO(281,312,playgame.G) >= playgame.yellowG_min) && (playgame.imgO(281,312,playgame.G) <= playgame.yellowG_max))
                send_command(playgame.arduino, "0000000100000000");
                playgame.trail_yellow = true;
            end
        end

        function playgame = find_trail_blue(playgame)
            if ((playgame.imgO(291,349,playgame.B) >= playgame.blueB_min) && (playgame.imgO(291,349,playgame.B) <= playgame.blueB_max) && ...
                (playgame.imgO(291,349,playgame.G) >= playgame.blueG_min) && (playgame.imgO(291,349,playgame.G) <= playgame.blueG_max) && ...
                (playgame.imgO(290,349,playgame.B) >= playgame.blueB_min) && (playgame.imgO(290,349,playgame.B) <= playgame.blueB_max) && ...
                (playgame.imgO(290,349,playgame.G) >= playgame.blueG_min) && (playgame.imgO(290,349,playgame.G) <= playgame.blueG_max) && ...
                (playgame.imgO(289,349,playgame.B) >= playgame.blueB_min) && (playgame.imgO(289,349,playgame.B) <= playgame.blueB_max) && ...
                (playgame.imgO(289,349,playgame.G) >= playgame.blueG_min) && (playgame.imgO(289,349,playgame.G) <= playgame.blueG_max) && ...
                (playgame.imgO(288,349,playgame.B) >= playgame.blueB_min) && (playgame.imgO(288,349,playgame.B) <= playgame.blueB_max) && ...
                (playgame.imgO(288,349,playgame.G) >= playgame.blueG_min) && (playgame.imgO(288,349,playgame.G) <= playgame.blueG_max) && ...
                (playgame.imgO(287,349,playgame.B) >= playgame.blueB_min) && (playgame.imgO(287,349,playgame.B) <= playgame.blueB_max) && ...
                (playgame.imgO(287,349,playgame.G) >= playgame.blueG_min) && (playgame.imgO(287,349,playgame.G) <= playgame.blueG_max) && ...
                (playgame.imgO(286,349,playgame.B) >= playgame.blueB_min) && (playgame.imgO(286,349,playgame.B) <= playgame.blueB_max) && ...
                (playgame.imgO(286,349,playgame.G) >= playgame.blueG_min) && (playgame.imgO(286,349,playgame.G) <= playgame.blueG_max) && ...
                (playgame.imgO(285,348,playgame.B) >= playgame.blueB_min) && (playgame.imgO(285,348,playgame.B) <= playgame.blueB_max) && ...
                (playgame.imgO(285,348,playgame.G) >= playgame.blueG_min) && (playgame.imgO(285,348,playgame.G) <= playgame.blueG_max) && ...
                (playgame.imgO(284,348,playgame.B) >= playgame.blueB_min) && (playgame.imgO(284,348,playgame.B) <= playgame.blueB_max) && ...
                (playgame.imgO(284,348,playgame.G) >= playgame.blueG_min) && (playgame.imgO(284,348,playgame.G) <= playgame.blueG_max) && ...
                (playgame.imgO(283,348,playgame.B) >= playgame.blueB_min) && (playgame.imgO(283,348,playgame.B) <= playgame.blueB_max) && ...
                (playgame.imgO(283,348,playgame.G) >= playgame.blueG_min) && (playgame.imgO(283,348,playgame.G) <= playgame.blueG_max) && ...
                (playgame.imgO(282,348,playgame.B) >= playgame.blueB_min) && (playgame.imgO(282,348,playgame.B) <= playgame.blueB_max) && ...
                (playgame.imgO(282,348,playgame.G) >= playgame.blueG_min) && (playgame.imgO(282,348,playgame.G) <= playgame.blueG_max) && ...
                (playgame.imgO(281,348,playgame.B) >= playgame.blueB_min) && (playgame.imgO(281,348,playgame.B) <= playgame.blueB_max) && ...
                (playgame.imgO(281,348,playgame.G) >= playgame.blueG_min) && (playgame.imgO(281,348,playgame.G) <= playgame.blueG_max) && ...
                (playgame.imgO(280,348,playgame.B) >= playgame.blueB_min) && (playgame.imgO(280,348,playgame.B) <= playgame.blueB_max) && ...
                (playgame.imgO(280,348,playgame.G) >= playgame.blueG_min) && (playgame.imgO(280,348,playgame.G) <= playgame.blueG_max) && ...
                (playgame.imgO(279,348,playgame.B) >= playgame.blueB_min) && (playgame.imgO(279,348,playgame.B) <= playgame.blueB_max) && ...
                (playgame.imgO(279,348,playgame.G) >= playgame.blueG_min) && (playgame.imgO(279,348,playgame.G) <= playgame.blueG_max))
                send_command(playgame.arduino, "0000000010000000");
                playgame.trail_blue = true;
            end
        end

        function playgame = find_trail_orange(playgame)
            if ((playgame.imgO(294,387,playgame.R) >= playgame.orangeR_min) && (playgame.imgO(294,387,playgame.G) <= playgame.orangeR_max) && ...
                (playgame.imgO(294,387,playgame.G) >= playgame.orangeG_min) && (playgame.imgO(294,387,playgame.G) <= playgame.orangeG_max) && ...
                (playgame.imgO(293,387,playgame.R) >= playgame.orangeR_min) && (playgame.imgO(293,387,playgame.R) <= playgame.orangeR_max) && ...
                (playgame.imgO(293,387,playgame.G) >= playgame.orangeG_min) && (playgame.imgO(293,387,playgame.G) <= playgame.orangeG_max) && ...
                (playgame.imgO(292,386,playgame.R) >= playgame.orangeR_min) && (playgame.imgO(292,386,playgame.R) <= playgame.orangeR_max) && ...
                (playgame.imgO(292,386,playgame.G) >= playgame.orangeG_min) && (playgame.imgO(292,386,playgame.G) <= playgame.orangeG_max) && ...
                (playgame.imgO(291,386,playgame.R) >= playgame.orangeR_min) && (playgame.imgO(291,386,playgame.R) <= playgame.orangeR_max) && ...
                (playgame.imgO(291,386,playgame.G) >= playgame.orangeG_min) && (playgame.imgO(291,386,playgame.G) <= playgame.orangeG_max) && ...
                (playgame.imgO(290,386,playgame.R) >= playgame.orangeR_min) && (playgame.imgO(290,386,playgame.R) <= playgame.orangeR_max) && ...
                (playgame.imgO(290,386,playgame.G) >= playgame.orangeG_min) && (playgame.imgO(290,386,playgame.G) <= playgame.orangeG_max) && ...
                (playgame.imgO(289,385,playgame.R) >= playgame.orangeR_min) && (playgame.imgO(289,385,playgame.R) <= playgame.orangeR_max) && ...
                (playgame.imgO(289,385,playgame.G) >= playgame.orangeG_min) && (playgame.imgO(289,385,playgame.G) <= playgame.orangeG_max) && ...
                (playgame.imgO(288,385,playgame.R) >= playgame.orangeR_min) && (playgame.imgO(288,385,playgame.R) <= playgame.orangeR_max) && ...
                (playgame.imgO(288,385,playgame.G) >= playgame.orangeG_min) && (playgame.imgO(288,385,playgame.G) <= playgame.orangeG_max) && ...
                (playgame.imgO(287,385,playgame.R) >= playgame.orangeR_min) && (playgame.imgO(287,385,playgame.R) <= playgame.orangeR_max) && ...
                (playgame.imgO(287,385,playgame.G) >= playgame.orangeG_min) && (playgame.imgO(287,385,playgame.G) <= playgame.orangeG_max) && ...
                (playgame.imgO(286,384,playgame.R) >= playgame.orangeR_min) && (playgame.imgO(286,384,playgame.R) <= playgame.orangeR_max) && ...
                (playgame.imgO(286,384,playgame.G) >= playgame.orangeG_min) && (playgame.imgO(286,384,playgame.G) <= playgame.orangeG_max) && ...
                (playgame.imgO(285,384,playgame.R) >= playgame.orangeR_min) && (playgame.imgO(285,384,playgame.R) <= playgame.orangeR_max) && ...
                (playgame.imgO(285,384,playgame.G) >= playgame.orangeG_min) && (playgame.imgO(285,384,playgame.G) <= playgame.orangeG_max) && ...
                (playgame.imgO(284,384,playgame.R) >= playgame.orangeR_min) && (playgame.imgO(284,384,playgame.R) <= playgame.orangeR_max) && ...
                (playgame.imgO(284,384,playgame.G) >= playgame.orangeG_min) && (playgame.imgO(284,384,playgame.G) <= playgame.orangeG_max) && ...
                (playgame.imgO(283,383,playgame.R) >= playgame.orangeR_min) && (playgame.imgO(283,383,playgame.R) <= playgame.orangeR_max) && ...
                (playgame.imgO(283,383,playgame.G) >= playgame.orangeG_min) && (playgame.imgO(283,383,playgame.G) <= playgame.orangeG_max) && ...
                (playgame.imgO(282,382,playgame.R) >= playgame.orangeR_min) && (playgame.imgO(282,382,playgame.R) <= playgame.orangeR_max) && ...
                (playgame.imgO(282,382,playgame.G) >= playgame.orangeG_min) && (playgame.imgO(282,382,playgame.G) <= playgame.orangeG_max))
                send_command(playgame.arduino, "0000000001000000");
                playgame.trail_orange = true;
            end
        end

        function playgame = tear_down(playgame)
            disp(playgame);
            %detect green
            if ((playgame.note_green) && ...
                ~((playgame.greenPixel >= playgame.green_min) && (playgame.greenPixel <= playgame.green_max)))
                send_command(playgame.arduino, "1000000000000000");
                playgame.note_green = false;
            elseif ((playgame.trail_green) && ...
                ~((playgame.greenPixel >= playgame.green_min) && (playgame.greenPixel <= playgame.green_max)))
                send_command(playgame.arduino, "0000010000000000");
                playgame.trail_green = false;
            end

            %detect red   
            if ((playgame.note_red) && ...
                ~((playgame.redPixel >= playgame.red_min) && (playgame.redPixel <= playgame.red_max)))
                send_command(playgame.arduino, "0100000000000000");
                playgame.note_red = false;
            elseif ((playgame.trail_red) && ...
                ~((playgame.redPixel >= playgame.red_min) && (playgame.redPixel <= playgame.red_max)))
                send_command(playgame.arduino, "0000001000000000");
                playgame.trail_red = false;
            end

            %detect yellow
            if ((playgame.note_yellow) && ...
                ~((playgame.yellowPixelR >= playgame.yellowR_min) && (playgame.yellowPixelR <= playgame.yellowR_max) && ...
                (playgame.yellowPixelG >= playgame.yellowG_min) && (playgame.yellowPixelG <= playgame.yellowG_max)))
                send_command(playgame.arduino, "0010000000000000");
                playgame.note_yellow = false;
            elseif ((playgame.trail_yellow) && ...
                ~((playgame.yellowPixelR >= playgame.yellowR_min) && (playgame.yellowPixelR <= playgame.yellowR_max) && ...
                (playgame.yellowPixelG >= playgame.yellowG_min) && (playgame.yellowPixelG <= playgame.yellowG_max)))
                send_command(playgame.arduino, "0000000100000000");
                playgame.trail_yellow = false;
            end

            %detect blue
            if ((playgame.note_blue) && ...
                ~((playgame.bluePixelG >= playgame.blueG_min) && (playgame.bluePixelG <= playgame.blueG_max) && ...
                (playgame.bluePixelB >= playgame.blueB_min) && (playgame.bluePixelB <= playgame.blueB_max)))
                send_command(playgame.arduino, "0001000000000000");
                playgame.note_blue = false;
            elseif ((playgame.trail_blue) && ...
                ~((playgame.bluePixelG >= playgame.blueG_min) && (playgame.bluePixelG <= playgame.blueG_max) && ...
                (playgame.bluePixelB >= playgame.blueB_min) && (playgame.bluePixelB <= playgame.blueB_max)))
                send_command(playgame.arduino, "0000000010000000");
                playgame.trail_blue = false;
            end

            %detect orange
            if ((playgame.note_orange) && ...
                ~((playgame.orangePixelR >= playgame.orangeR_min) && (playgame.orangePixelR <= playgame.orangeR_max) && ...
                (playgame.orangePixelG >= playgame.orangeG_min) && (playgame.orangePixelG <= playgame.orangeG_max)))
                send_command(playgame.arduino, "0000100000000000");
                playgame.note_orange = false;
            elseif ((playgame.trail_orange) && ...
                ~((playgame.orangePixelR >= playgame.orangeR_min) && (playgame.orangePixelR <= playgame.orangeR_max) && ...
                (playgame.orangePixelG >= playgame.orangeG_min) && (playgame.orangePixelG <= playgame.orangeG_max)))
                send_command(playgame.arduino, "0000000001000000");
                playgame.trail_orange = false;
            end
        end
        % function img = get_imgO(y, x, color)
        %     img = playgame.imgO(y, x, color);
        % end
    end
end