classdef DetectedImage
    properties (Constant)
        % cores
        R = 1;
        G = 2;
        B = 3;

        % colors configuration
        red_min = 175;
        red_max = 255;
        green_min = 175;
        green_max = 255;
        yellowR_min = 175;
        yellowR_max = 255;
        yellowG_min = 150;
        yellowG_max = 255;
        blueG_min = 125;
        blueG_max = 255;
        blueB_min = 175;
        blueB_max = 255;
        orangeR_min = 175;
        orangeR_max = 255;
        orangeG_min = 95;
        orangeG_max = 255;

        % pixels that simple notes analyse
        greenPixel;
        redPixel;
        yellowPixelR;
        yellowPixelG;
        bluePixelG;
        bluePixelB;
        orangePixelR;
        orangePixelG;
    end

    properties
        % if trail was detected (array of boolean)
        simple_note_detection;
        trail_detection;
        trail_last_note_detection;
    end

    methods
        function DetectedImage()
            
            % situacao de notas simples
            keys = {'green', 'red', 'yellow', 'blue', 'orange'};
            values = [false false false false false];
            simple_note_detection = containers.Map(keys, values);

            % situacao de rastro das cores
            keys = {'green', 'red', 'yellow', 'blue', 'orange'};
            values = [false false false false false];
            trail_detection = containers.Map(keys, values);

            % situacao de rastro das cores
            keys = {'green', 'red', 'yellow', 'blue', 'orange'};
            values = [false false false false false];
            trail_last_note_detection = containers.Map(keys, values);

            % cores
            R = 1;
            G = 2;
            B = 3;

            % colors configuration
            red_min = 175;
            red_max = 255;
            green_min = 175;
            green_max = 255;
            yellowR_min = 175;
            yellowR_max = 255;
            yellowG_min = 150;
            yellowG_max = 255;
            blueG_min = 125;
            blueG_max = 255;
            blueB_min = 175;
            blueB_max = 255;
            orangeR_min = 175;
            orangeR_max = 255;
            orangeG_min = 95;
            orangeG_max = 255;
        end

        function reset()
            % situacao de notas simples
            keys = {'green', 'red', 'yellow', 'blue', 'orange'};
            values = [false false false false false];
            simple_note_detection = containers.Map(keys, values);

            % situacao de rastro das cores
            keys = {'green', 'red', 'yellow', 'blue', 'orange'};
            values = [false false false false false];
            trail_detection = containers.Map(keys, values);

            % situacao de rastro das cores
            keys = {'green', 'red', 'yellow', 'blue', 'orange'};
            values = [false false false false false];
            trail_last_note_detection = containers.Map(keys, values);
        end;

        %detect green
        function setSimpleDetetion()
            
            % Pixels
            greenPixel = imgO(312,230,G);
            redPixel = imgO(311,274,R);
            yellowPixelR = imgO(312,311,R);
            yellowPixelG = imgO(312,311,G);
            bluePixelG = imgO(312,354,G);
            bluePixelB = imgO(312,354,B);
            orangePixelR = imgO(311,395,R);
            orangePixelG = imgO(311,395,G);

            %detect green
            if( greenPixel >= green_min && greenPixel <= green_max )
                simple_note_detection('green') = true;
            end

            %detect red   
            if( redPixel >= red_min && redPixel <= red_max )
                simple_note_detection('red') = true;
            end

            %detect yellow
            if (yellowPixelR >= yellowR_min && yellowPixelR <= yellowR_max && ...
                yellowPixelG >= yellowG_min && yellowPixelG <= yellowG_max)
                simple_note_detection('yellow') = true;
            end

            %detect blue
            if (bluePixelG >= blueG_min && bluePixelG <= blueG_max && ...
                bluePixelB >= blueB_min && bluePixelB <= blueB_max)
                simple_note_detection('blue') = true;
            end

            %detect orange
            if  (orangePixelR >= orangeR_min && orangePixelR <= orangeR_max && ...
                orangePixelG >= orangeG_min && orangePixelG <= orangeG_max)
                simple_note_detection('orange') = true;
            end
        
        end
        
        function setTrailDetection(imgO)
            if ((imgO(293,238,G) >= green_min && imgO(293,238,G) <= green_max) && ...
                (imgO(292,238,G) >= green_min && imgO(292,238,G) <= green_max) && ...
                (imgO(291,239,G) >= green_min && imgO(291,239,G) <= green_max) && ...
                (imgO(290,239,G) >= green_min && imgO(290,239,G) <= green_max) && ...
                (imgO(289,239,G) >= green_min && imgO(289,239,G) <= green_max) && ...
                (imgO(288,240,G) >= green_min && imgO(288,240,G) <= green_max) && ...
                (imgO(287,240,G) >= green_min && imgO(287,240,G) <= green_max) && ...
                (imgO(286,240,G) >= green_min && imgO(286,240,G) <= green_max) && ...
                (imgO(285,241,G) >= green_min && imgO(285,241,G) <= green_max) && ...
                (imgO(284,241,G) >= green_min && imgO(284,241,G) <= green_max) && ...
                (imgO(283,241,G) >= green_min && imgO(283,241,G) <= green_max) && ...
                (imgO(282,242,G) >= green_min && imgO(282,242,G) <= green_max) && ...
                (imgO(281,243,G) >= green_min && imgO(281,243,G) <= green_max) )
                trail_detection('green') = true;
            end

            if ((imgO(293,275,R) >= red_min && imgO(293,275,R) <= red_max) && ...
                (imgO(292,275,R) >= red_min && imgO(292,275,R) <= red_max) && ...
                (imgO(291,275,R) >= red_min && imgO(291,275,R) <= red_max) && ...
                (imgO(290,276,R) >= red_min && imgO(290,276,R) <= red_max) && ...
                (imgO(289,276,R) >= red_min && imgO(289,276,R) <= red_max) && ...
                (imgO(288,276,R) >= red_min && imgO(288,276,R) <= red_max) && ...
                (imgO(287,276,R) >= red_min && imgO(287,276,R) <= red_max) && ...
                (imgO(286,276,R) >= red_min && imgO(286,276,R) <= red_max) && ...
                (imgO(285,277,R) >= red_min && imgO(285,277,R) <= red_max) && ...
                (imgO(284,277,R) >= red_min && imgO(284,277,R) <= red_max) && ...
                (imgO(283,277,R) >= red_min && imgO(283,277,R) <= red_max) && ...
                (imgO(282,277,R) >= red_min && imgO(282,277,R) <= red_max) && ...
                (imgO(281,278,R) >= red_min && imgO(281,278,R) <= red_max))
                trail_detection('red') = true;
            end

            if ((imgO(293,312,R) >= yellowR_min && imgO(293,312,R) <= yellowR_max) && ...
                (imgO(293,312,G) >= yellowG_min && imgO(293,312,G) <= yellowG_max) && ...
                (imgO(292,312,R) >= yellowR_min && imgO(292,312,R) <= yellowR_max) && ...
                (imgO(292,312,G) >= yellowG_min && imgO(292,312,G) <= yellowG_max) && ...
                (imgO(291,312,R) >= yellowR_min && imgO(291,312,R) <= yellowR_max) && ...
                (imgO(291,312,G) >= yellowG_min && imgO(291,312,G) <= yellowG_max) && ...
                (imgO(290,312,R) >= yellowR_min && imgO(290,312,R) <= yellowR_max) && ...
                (imgO(290,312,G) >= yellowG_min && imgO(290,312,G) <= yellowG_max) && ...
                (imgO(289,312,R) >= yellowR_min && imgO(289,312,R) <= yellowR_max) && ...
                (imgO(289,312,G) >= yellowG_min && imgO(289,312,G) <= yellowG_max) && ...
                (imgO(288,312,R) >= yellowR_min && imgO(288,312,R) <= yellowR_max) && ...
                (imgO(288,312,G) >= yellowG_min && imgO(288,312,G) <= yellowG_max) && ...
                (imgO(287,312,R) >= yellowR_min && imgO(287,312,R) <= yellowR_max) && ...
                (imgO(287,312,G) >= yellowG_min && imgO(287,312,G) <= yellowG_max) && ...
                (imgO(286,312,R) >= yellowR_min && imgO(286,312,R) <= yellowR_max) && ...
                (imgO(286,312,G) >= yellowG_min && imgO(286,312,G) <= yellowG_max) && ...
                (imgO(285,312,R) >= yellowR_min && imgO(285,312,R) <= yellowR_max) && ...
                (imgO(285,312,G) >= yellowG_min && imgO(285,312,G) <= yellowG_max) && ...
                (imgO(284,312,R) >= yellowR_min && imgO(284,312,R) <= yellowR_max) && ...
                (imgO(284,312,G) >= yellowG_min && imgO(284,312,G) <= yellowG_max) && ...
                (imgO(283,312,R) >= yellowR_min && imgO(283,312,R) <= yellowR_max) && ...
                (imgO(283,312,G) >= yellowG_min && imgO(283,312,G) <= yellowG_max) && ...
                (imgO(282,312,R) >= yellowR_min && imgO(282,312,R) <= yellowR_max) && ...
                (imgO(282,312,G) >= yellowG_min && imgO(282,312,G) <= yellowG_max) && ...
                (imgO(281,312,R) >= yellowR_min && imgO(281,312,R) <= yellowR_max) && ...
                (imgO(281,312,G) >= yellowG_min && imgO(281,312,G) <= yellowG_max))
                trail_detection('yellow') = true;
            end

            if ((imgO(291,349,B) >= blueB_min && imgO(291,349,B) <= blueB_max) && ...
                (imgO(291,349,G) >= blueG_min && imgO(291,349,G) <= blueG_max) && ...
                (imgO(290,349,B) >= blueB_min && imgO(290,349,B) <= blueB_max) && ...
                (imgO(290,349,G) >= blueG_min && imgO(290,349,G) <= blueG_max) && ...
                (imgO(289,349,B) >= blueB_min && imgO(289,349,B) <= blueB_max) && ...
                (imgO(289,349,G) >= blueG_min && imgO(289,349,G) <= blueG_max) && ...
                (imgO(288,349,B) >= blueB_min && imgO(288,349,B) <= blueB_max) && ...
                (imgO(288,349,G) >= blueG_min && imgO(288,349,G) <= blueG_max) && ...
                (imgO(287,349,B) >= blueB_min && imgO(287,349,B) <= blueB_max) && ...
                (imgO(287,349,G) >= blueG_min && imgO(287,349,G) <= blueG_max) && ...
                (imgO(286,349,B) >= blueB_min && imgO(286,349,B) <= blueB_max) && ...
                (imgO(286,349,G) >= blueG_min && imgO(286,349,G) <= blueG_max) && ...
                (imgO(285,348,B) >= blueB_min && imgO(285,348,B) <= blueB_max) && ...
                (imgO(285,348,G) >= blueG_min && imgO(285,348,G) <= blueG_max) && ...
                (imgO(284,348,B) >= blueB_min && imgO(284,348,B) <= blueB_max) && ...
                (imgO(284,348,G) >= blueG_min && imgO(284,348,G) <= blueG_max) && ...
                (imgO(283,348,B) >= blueB_min && imgO(283,348,B) <= blueB_max) && ...
                (imgO(283,348,G) >= blueG_min && imgO(283,348,G) <= blueG_max) && ...
                (imgO(282,348,B) >= blueB_min && imgO(282,348,B) <= blueB_max) && ...
                (imgO(282,348,G) >= blueG_min && imgO(282,348,G) <= blueG_max) && ...
                (imgO(281,348,B) >= blueB_min && imgO(281,348,B) <= blueB_max) && ...
                (imgO(281,348,G) >= blueG_min && imgO(281,348,G) <= blueG_max) && ...
                (imgO(280,348,B) >= blueB_min && imgO(280,348,B) <= blueB_max) && ...
                (imgO(280,348,G) >= blueG_min && imgO(280,348,G) <= blueG_max) && ...
                (imgO(279,348,B) >= blueB_min && imgO(279,348,B) <= blueB_max) && ...
                (imgO(279,348,G) >= blueG_min && imgO(279,348,G) <= blueG_max))
                trail_detection('blue') = true;
            end

            if ((imgO(294,387,R) >= orangeR_min && imgO(294,387,G) <= orangeR_max) && ...
                (imgO(294,387,G) >= orangeG_min && imgO(294,387,G) <= orangeG_max) && ...
                (imgO(293,387,R) >= orangeR_min && imgO(293,387,R) <= orangeR_max) && ...
                (imgO(293,387,G) >= orangeG_min && imgO(293,387,G) <= orangeG_max) && ...
                (imgO(292,386,R) >= orangeR_min && imgO(292,386,R) <= orangeR_max) && ...
                (imgO(292,386,G) >= orangeG_min && imgO(292,386,G) <= orangeG_max) && ...
                (imgO(291,386,R) >= orangeR_min && imgO(291,386,R) <= orangeR_max) && ...
                (imgO(291,386,G) >= orangeG_min && imgO(291,386,G) <= orangeG_max) && ...
                (imgO(290,386,R) >= orangeR_min && imgO(290,386,R) <= orangeR_max) && ...
                (imgO(290,386,G) >= orangeG_min && imgO(290,386,G) <= orangeG_max) && ...
                (imgO(289,385,R) >= orangeR_min && imgO(289,385,R) <= orangeR_max) && ...
                (imgO(289,385,G) >= orangeG_min && imgO(289,385,G) <= orangeG_max) && ...
                (imgO(288,385,R) >= orangeR_min && imgO(288,385,R) <= orangeR_max) && ...
                (imgO(288,385,G) >= orangeG_min && imgO(288,385,G) <= orangeG_max) && ...
                (imgO(287,385,R) >= orangeR_min && imgO(287,385,R) <= orangeR_max) && ...
                (imgO(287,385,G) >= orangeG_min && imgO(287,385,G) <= orangeG_max) && ...
                (imgO(286,384,R) >= orangeR_min && imgO(286,384,R) <= orangeR_max) && ...
                (imgO(286,384,G) >= orangeG_min && imgO(286,384,G) <= orangeG_max) && ...
                (imgO(285,384,R) >= orangeR_min && imgO(285,384,R) <= orangeR_max) && ...
                (imgO(285,384,G) >= orangeG_min && imgO(285,384,G) <= orangeG_max) && ...
                (imgO(284,384,R) >= orangeR_min && imgO(284,384,R) <= orangeR_max) && ...
                (imgO(284,384,G) >= orangeG_min && imgO(284,384,G) <= orangeG_max) && ...
                (imgO(283,383,R) >= orangeR_min && imgO(283,383,R) <= orangeR_max) && ...
                (imgO(283,383,G) >= orangeG_min && imgO(283,383,G) <= orangeG_max) && ...
                (imgO(282,382,R) >= orangeR_min && imgO(282,382,R) <= orangeR_max) && ...
                (imgO(282,382,G) >= orangeG_min && imgO(282,382,G) <= orangeG_max))
                trail_detection('orange') = true;
            end
        end

        function setTrailLastNoteDetection(imgO)

            if (imgO(312,230,G) >= green_min && imgO(312,230,G) <= green_max)
                trail_last_note_detection('green') = true;
            end;

            if (imgO(311,274,R) >= red_min && imgO(311,274,R) <= red_max)
                trail_last_note_detection('red') = true;
            end;

            if (imgO(312,311,R) >= yellowR_min && imgO(312,311,R) <= yellowR_max && ...
                imgO(312,311,G) >= yellowG_min && imgO(312,311,G) <= yellowG_max)
                trail_last_note_detection('yellow') = true;
            end;

            if (imgO(312,311,B) >= blueB_min && imgO(312,311,B) <= blueB_max && ...
                imgO(312,311,G) >= blueG_min && imgO(312,311,G) <= blueG_max)
                trail_last_note_detection('blue') = true;
            end;

            if (imgO(312,311,R) >= orangeR_min && imgO(312,311,R) <= orangeR_max && ...
                imgO(312,311,G) >= orangeG_min && imgO(312,311,G) <= orangeG_max)
                trail_last_note_detection('orange') = true;
            end;

        end;

        function getTrailDetection(note)
            return trail_detection(note);
        end

        function getSimpleDetection(note)
            return simple_note_detection(note);
        end

        function getTrailLastNoteDetection(note)
            return trail_last_note_detection(note);
        end;

    end
end